### ISSUE TITLE
Validate role should validate the connectivity to the fabric in the beginning of the playbook validate role

### ISSUE THREAD

**Issue by juburnet** [netascode/ansible-dc-vxlan#104]
I suggest to check the communication and credentials to the ndfc, in the beginning of the playbook and validate role so that it will fail fast rather than doing all of the validation, prepare and build steps first.
"List fabric" could be used to test connectivity in the beginning.

**Comment by mikewiebe** [comment]
Just noticed you added this @juburnet .. this is a good idea!
