### ISSUE TITLE
Create/Deploy/Remove roles depend on Validate role

### ISSUE THREAD

**Issue by marehler** [netascode/ansible-dc-vxlan#120]
The validate role can be executed individually, however the create, deploy, and remove roles depend on the validate role which creates the service model. Executing these roles individually fails:

````
TASK [cisco.nac_dc_vxlan.common : ansible.builtin.fail] *********************************************************************************************
fatal: [marehler_vnd2]: FAILED! => {"changed": false, "msg": "Service Model Not Defined.  Role cisco.nac_dc_vxlan.validate Must Be Called First"}
````

For a CI/CD workflow integration it might be desirable to execute all roles in different stages, i.e. execute one role per stage. Running the validate role in a "Validate" stage, and again in "Create" and "Deploy" stages for re-creating the service model would be duplicate effort and time.

**Comment by mtarking** [comment]
Indeed the validate role is a dependency as the rendered in-memory data model and subsequent massaging of the runtime model is rendered from the model validation. To make what you describe as achievable, the validate role has been added as an dependency to each role in the latest release (0.2.0). The validate role to-date only takes about ~1 sec to run.

I'm going to close this issue for now as this the current intended functionality. We can revisit if any complications are seen.

**Comment by marehler** [comment]
Verified. Works fine, if you execute the create and/or deploy role only, the validate role is now included automatically.
