### ISSUE TITLE
Control Parameter Documentation

### ISSUE THREAD

**Issue by mikewiebe** [netascode/ansible-dc-vxlan#177]
We need to update our main readme and example repo readme with a section dedicated to the various control parameters.

These are the control parameters we have today:

interface_delete_mode: false
network_delete_mode: false
vrf_delete_mode: false
inventory_delete_mode: false
vpc_delete_mode: false
link_vpc_delete_mode: false
force_run_all: false

**Comment by mtarking** [comment]
Completed as part of #172
