### ISSUE TITLE
Policy: Freeform (to be worked first)

### ISSUE THREAD

**Issue by mikewiebe** [netascode/ansible-dc-vxlan#67]
Recursive processing and discovery of `freeform` directory under `host_vars/[fabric_name]`

**Comment by juburnet** [comment]
This was merged June 18th - mikewiebe merged commit [35e926b](https://github.com/CiscoDevNet/ansible-dcnm/commit/35e926bb78db72814cc8316f9f1763ce4b2cfd6e) into CiscoDevNet:develop [on Jun 18](https://github.com/CiscoDevNet/ansible-dcnm/pull/285#event-13200701300)

**Comment by mtarking** [comment]
The initial policy framework was completed in #178.
Remove capabilities need to be completed still.

**Comment by juburnet** [comment]
Update role: remove to remove the policy from NDFC/Device when it gets removed from the data model

Query what NDFC has as state vs what we have in data model.  Delete those in diff.  
Matt will continue to implement and we will test.
