### ISSUE TITLE
Policy: Infrastructure

### ISSUE THREAD

**Issue by mikewiebe** [netascode/ansible-dc-vxlan#70]
For each feature that we are defining in our data model (VRF-Lite, ACLs, RouteMaps etc...) we need to design the infrastructure to do the following:

* Translate datamodel to jinja2 template
* Translate jinja2 rendered CLI to dcnm_policy module

**Comment by mtarking** [comment]
The initial part of this issue was completed by #178. Subsequent parts will be completed by #154 #155 #156 #157 #158
