### ISSUE TITLE
Policy: Freeform (Validate Task)

### ISSUE THREAD

**Issue by rafmuller** [netascode/ansible-dc-vxlan#72]
This issue to track the PR focused on the validate task of loading up the template files located under the host vars.

**Comment by juburnet** [comment]
@mtarking and @rafmuller  - please confirm if this Issue is still required after what we have completed in https://github.com/netascode/ansible-dc-vxlan/pull/178

**Comment by mtarking** [comment]
The template files are loaded via native Ansible plugins and filters in #178. Closing this issue.
